apiVersion: v1
kind: Service
metadata:
  name: service-produtos
  namespace: urbanfood
  labels:
    app: app-produtos
spec:
  ports:
  - name: service-produtos-http
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: app-produtos
  type: LoadBalancer